name: Sanity check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      boto3_version:
        description: Target boto3 version
        required: false

jobs:
  sanity-check:
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Extract versions
        id: vars
        uses: actions/github-script@v6
        with:
          script: |
            const { extractVersionsFromInput } = require('./.github/workflows/helpers.js')
            await extractVersionsFromInput({ core, context })
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install boto3
        env:
          BOTO3_VERSION: ${{ steps.vars.outputs.boto3-version }}
          BOTOCORE_VERSION: ${{ steps.vars.outputs.botocore-version }}
        run: |
          python -m pip install -U boto3==${BOTO3_VERSION} botocore==${BOTOCORE_VERSION}
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install -n
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Build packages
        env:
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          rm -rf mypy_boto3_output/*
          python -m mypy_boto3_builder mypy_boto3_output --product boto3 boto3-services -b $VERSION
      - name: Install master packages
        run: |
          ./scripts/install.sh master
      - name: Check output
        run: |
          python ./scripts/check_output.py -p ./mypy_boto3_output
